<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit77d63c3f54e3f7dd796f40107d39af4a
{
    public static $prefixLengthsPsr4 = array (
        'OC' => 
        array (
            'OCDDelivery\\' => 23,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'OCDDelivery\\' => 
        array (
            0 => __DIR__ . '/..' . '/ocsrc',
        ),
    );

    public static $prefixesPsr0 = array (
        'D' => 
        array (
            'DDelivery' => 
            array (
                0 => __DIR__ . '/..' . '/sdk/classes',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit77d63c3f54e3f7dd796f40107d39af4a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit77d63c3f54e3f7dd796f40107d39af4a::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit77d63c3f54e3f7dd796f40107d39af4a::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
